name: smartapp_project24
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  calendar_view: ^1.1.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^17.1.0
  flutter_timezone: ^1.0.8
  google_fonts: 6.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
